#!/usr/bin/env python3
"""Embed a shader source file as a C string literal."""
import sys


def main() -> None:
    source_path, header_path = sys.argv[1], sys.argv[2]
    symbol = sys.argv[3] if len(sys.argv) > 3 else "kShaderSource"
    with open(source_path, "r", encoding="utf-8") as f:
        source = f.read()

    escaped = source.replace("\\", "\\\\").replace('"', '\\"').replace("\n", '\\n"\n"')

    with open(header_path, "w", encoding="utf-8") as f:
        f.write("// generated by tools/embed_shader.py - do not edit\n")
        f.write("static const char %s[] =\n" % symbol)
        f.write('"%s";\n' % escaped)


if __name__ == "__main__":
    main()
